require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Layout/LineLength:
  Max: 130
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
  
RSpec/ExampleLength:
  Exclude: 
    - spec/system/*
    - spec/system/admin/*

RSpec/MultipleExpectations:
  Exclude: 
    - spec/system/* 
    - spec/system/admin/* 
    
RSpec/LetSetup:
  Exclude:
    - spec/system/admin/* 
